name: portfolio_app
description: A portfolio App to showcase projects.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter


  font_awesome_flutter: ^10.5.0
  responsive_builder: ^0.7.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
