name: portfolio_app
description: "Portfolio Web App for showcasing projects and skills"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.8.0-222.0.dev

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.3
  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  provider: ^6.1.4
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Aman Sikarwar.png